# Generated by Django 5.1.3 on 2024-12-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('ai', 'AI'), ('cs', 'CS'), ('it', 'IT'), ('is', 'IS'), ('ds', 'DS')], max_length=10),
        ),
    ]
